<a href="https://colab.research.google.com/github/KavyaSP2808/AIML-/blob/project/Python%20libraries/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Creating Arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

# Array with specific values
zeros = np.zeros((2,3))
ones = np.ones((3,3))
identity = np.eye(4)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)

# Range and linspace
arange_arr = np.arange(0, 10, 3)
linspace_arr = np.linspace(0, 1, 5)

print("Arange:", arange_arr)
print("Linspace:", linspace_arr)

# Random numbers
rand_arr = np.random.rand(2,3)
print("Random Array:\n", rand_arr)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Arange: [0 3 6 9]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Random Array:
 [[0.46982163 0.55486688 0.79636269]
 [0.04490311 0.10489549 0.7166921 ]]


In [2]:
# Example 1: Reshape and Transpose
matrix = np.arange(1, 13).reshape(2,6)
print("Matrix:\n", matrix)
print("Transpose:\n", matrix.T)

# Example 2: Mathematical operations
arr = np.array([10, 20, 30, 40])
print("Original Array:", arr)
print("Array + 5:", arr + 5)
print("Array squared:", arr ** 2)

# Example 3: Aggregate Functions
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

# Example 4: Matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n", np.dot(A,B))

# Example 5: Sorting
unsorted = np.array([3,1,4,1,5,9])
print("Sorted Array:", np.sort(unsorted))

Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Transpose:
 [[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
Original Array: [10 20 30 40]
Array + 5: [15 25 35 45]
Array squared: [ 100  400  900 1600]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949
Matrix Multiplication:
 [[19 22]
 [43 50]]
Sorted Array: [1 1 3 4 5 9]
